title: Urmanpreet Singh
logo: https://github.com/urmanml/Portfolio/blob/main/profile%20square%20(2).jpg
description: Data Science Portfolio
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
